#!/usr/bin/env python
# PYTHON_ARGCOMPLETE_OK
import sys
import argparse
import argcomplete
import pyperclip
from fonts import subscript, emoji, smallcaps, bold, handwriting, italic, demonic, bold, fancy

fonts = {
    'subscript': subscript.table,
    'emoji': emoji.table,
    'smallcaps': smallcaps.table,
    'bold': bold.table,
    'handwriting': handwriting.table,
    'italic': italic.table,
    'demonic': demonic.table,
    'bold': bold.table,
    'fancy': fancy.table,
}

parser = argparse.ArgumentParser(
    description="A font converter utility with the extra fonts included in utf8.")
parser.add_argument('text', nargs='*',
                    help="text to process")
parser.add_argument('-c', '--copy', action="store_true",
                    help="copies processed text to clipboard")
parser.add_argument('-f', '--font', default='subscript', choices=fonts, metavar='FONT',
                    help="which font to use")
parser.add_argument('--list-fonts', action="store_true",
                    help="list all supported fonts")
argcomplete.autocomplete(parser)
args = parser.parse_args()

if args.list_fonts:
    print(
        "Fonts:",
        *(f"{font.translate(fonts[font])} ({font})" for font in fonts),
        sep='\n • ',
    )
    quit()

if args.text:
    text = " ".join(args.text)
else:
    text = input('> ')

processed_text = text.translate(fonts[args.font])

if args.copy:
    pyperclip.copy(processed_text)
else:
    print(processed_text)
