#!/usr/bin/env python
# PYTHON_ARGCOMPLETE_OK
import sys
import argparse
import argcomplete
import pyperclip
import fonts

fonts = {
    'subscript': fonts.subscript,
    'emoji': fonts.emoji,
    'smallcaps': fonts.smallcaps,
    'bold': fonts.bold,
    'handwriting': fonts.handwriting,
    'italic': fonts.italic,
    'demonic': fonts.demonic,
    'bold': fonts.bold,
    'fancy': fonts.fancy,
}

parser = argparse.ArgumentParser(
    description="A font converter utility with the extra fonts included in utf8.")
parser.add_argument('text', nargs='*',
                    help="text to process")
parser.add_argument('-c', '--copy', action="store_true",
                    help="copies processed text to clipboard")
parser.add_argument('-f', '--font', default='subscript', choices=fonts, metavar='FONT',
                    help="which font to use")
parser.add_argument('--list-fonts', action="store_true",
                    help="list all supported fonts")
argcomplete.autocomplete(parser)
args = parser.parse_args()

if args.list_fonts:
    print(
        "Fonts:",
        *(f"{font.translate(fonts[font])} ({font})" for font in fonts),
        sep='\n • ',
    )
    quit()

if args.text:
    text = " ".join(args.text)
else:
    text = input('> ')

processed_text = text.translate(fonts[args.font])

if args.copy:
    pyperclip.copy(processed_text)
else:
    print(processed_text)
